Redo: fix: scripts/rust-envvars needs .venv/bin/python (#7394)
Redo of https://github.com/getsentry/snuba/pull/7384

---------

Co-authored-by: Joshua Li <joshuarli98@gmail.com>

diff --git a/scripts/rust-envvars b/scripts/rust-envvars
--- a/scripts/rust-envvars
+++ b/scripts/rust-envvars
@@ -1,3 +1,10 @@
+export REPOROOT="$(git rev-parse --show-toplevel)"
+
+if [ -z "${CI:-}" ] && [ ! -f "${REPOROOT}/.venv/bin/python" ]; then
+  echo "cannot source this file unless ${REPOROOT}/.venv/bin/python exists, please run devenv sync"
+  exit 1
+fi
+
 # Related thread: https://github.com/PyO3/pyo3/issues/1741
 
 # This is required for the tests in python.rs
@@ -5,7 +12,11 @@ export SNUBA_TEST_PYTHONPATH="$(python -c 'import sys; print(":".join(sys.path))
 export SNUBA_TEST_PYTHONEXECUTABLE="$(python -c 'import sys; print(sys.executable)')"
 
 # https://github.com/astral-sh/uv/issues/8821
-export PYTHONHOME="$(dirname $(dirname $(realpath $(which python))))"
+if [ -z "${CI:-}" ]; then
+  export PYTHONHOME="$(dirname $(dirname $(realpath "${REPOROOT}/.venv/bin/python")))"
+else
+  export PYTHONHOME="$(dirname $(dirname $(realpath "$(command -v python)")))"
+fi
 
 # load cargo envvars explicitly in case user forgot
 if [ -n "$FISH_VERSION" ]; then
