feat(ci): Build Arm64 Snuba Docker image (#2165)
We use docker cross-arch building to generate `linux/arm64` images.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -92,6 +92,52 @@ jobs:
           docker push ghcr.io/getsentry/snuba-ci:${{ github.sha }}
           docker push ghcr.io/getsentry/snuba-ci:latest
 
+  # For now, we cannot build linux/arm64 images on Linux hosts since
+  # |docker buildx ls| does not list arm64 as an option.
+  #
+  # This step does not have a set timeout because it is very slow. This is due
+  # because emulation required (this is running on an Intel host rather than an arm64 host)
+  # and that many Python packages do not have arm wheels, thus, requirying to build them from source.
+  # Upgrading Python package versions + giving access to a cache could improve things a lot
+  snuba-arm64-image:
+    name: "Docker Arm64 build"
+    runs-on: macos-11
+    env:
+      SNUBA_IMAGE: ghcr.io/getsentry/snuba-ci
+    steps:
+      - uses: actions/checkout@v2
+        name: Checkout code
+
+      - name: Set up Docker
+        run: |
+          brew install --cask docker
+          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+          open -a /Applications/Docker.app --args --unattended --accept-license
+          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
+
+      - name: Registry login
+        run: |
+          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
+
+      - name: Create Image
+        run: |
+          docker buildx create --name arm64-builder --use
+          docker buildx inspect --bootstrap
+          docker buildx build --platform linux/arm64 --cache-from $SNUBA_IMAGE:latest \
+            -t $SNUBA_IMAGE:${{ github.sha }} -t $SNUBA_IMAGE:latest --load .
+
+      - name: Publish
+        # Forks cannot push to the getsentry org
+        if: github.repository_owner == 'getsentry'
+        env:
+          branch: ${{ github.ref }}
+        run: |
+          docker push $SNUBA_IMAGE:${{ github.sha }}
+          if [ "${branch}" == 'refs/head/master']; then
+            docker push $SNUBA_IMAGE:latest
+          fi
+
   tests:
     needs: [linting, snuba-image]
     name: Tests and code coverage
@@ -134,7 +180,7 @@ jobs:
   sentry:
     needs: [snuba-image]
     runs-on: ubuntu-latest
-    timeout-minutes: 30
+    timeout-minutes: 90
 
     strategy:
       matrix:
